// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var pair = [
  "name",
  "age"
];

var triple = [
  "hello",
  1,
  true
];

console.log("pair=>", pair);

console.log("triple=>", triple);

var first = "hello";

var second = "age";

console.log("second=>", second);

console.log("first=>", first);

console.log("third=>", true);

function pattern_match(triple) {
  switch (triple[0]) {
    case "hello" :
        if (triple[1] === 1 && !triple[2]) {
          console.log("first");
          return ;
        }
        break;
    case "none" :
        if (triple[1] === 1 && !triple[2]) {
          console.log("second");
          return ;
        }
        break;
    default:
      
  }
  if (triple[2]) {
    console.log("third");
  } else {
    console.log("default");
  }
  
}

pattern_match(triple);

var third = true;

exports.pair = pair;
exports.triple = triple;
exports.second = second;
exports.first = first;
exports.third = third;
exports.pattern_match = pattern_match;
/*  Not a pure module */
