// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

function readFileAsLines(filename, trim) {
  var fileContents = Fs.readFileSync(filename, "utf8");
  return Belt_List.fromArray((
                trim ? fileContents.trim() : fileContents
              ).split("\n"));
}

function inputFilename(tag) {
  return "input/" + (tag + ".txt");
}

function readInputLines(trimOpt, tag) {
  var trim = trimOpt !== undefined ? trimOpt : true;
  return readFileAsLines(inputFilename(tag), trim);
}

readInputLines(undefined, "q1in");

console.log("hello!");

exports.readFileAsLines = readFileAsLines;
exports.inputFilename = inputFilename;
exports.readInputLines = readInputLines;
/*  Not a pure module */
