// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Yo$Aoc2017 = require("./yo.bs.js");

function test(param) {
  return Yo$Aoc2017.SayYo.speak(undefined);
}

Yo$Aoc2017.SayYo.speak(undefined);

exports.test = test;
/*  Not a pure module */
