// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var lines = Fs.readFileSync("input/q2in.txt", "utf8").trim().split("\n");

function parseInts(line) {
  return Belt_Array.map(line.split("\t"), Caml_format.caml_int_of_string);
}

console.log("input=>", lines);

var input = Belt_Array.map(lines, parseInts);

var liness = Fs.readFileSync("input/testj.json", "utf8");

console.log("lines=>", liness);

function part1(param) {
  return Belt_Array.reduce(Belt_Array.map(input, (function (row) {
                    return Belt_Array.reduce(row, Pervasives.min_int, (function (prim, prim$1) {
                                  if (prim > prim$1) {
                                    return prim;
                                  } else {
                                    return prim$1;
                                  }
                                })) - Belt_Array.reduce(row, Pervasives.max_int, (function (prim, prim$1) {
                                  if (prim < prim$1) {
                                    return prim;
                                  } else {
                                    return prim$1;
                                  }
                                })) | 0;
                  })), 0, (function (prim, prim$1) {
                return prim + prim$1 | 0;
              }));
}

exports.input = input;
exports.liness = liness;
exports.part1 = part1;
/* lines Not a pure module */
