// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var arr = Belt_Array.map(Fs.readFileSync("input/q5in.txt", "utf8").trim().split("\n"), Caml_format.caml_int_of_string);

var len = arr.length;

var pos = {
  contents: 0
};

function getJump(arr, pos) {
  var e = Belt_Array.get(arr, pos.contents);
  if (e !== undefined) {
    return e;
  } else {
    return 0;
  }
}

function part1(arr, pos, _step) {
  while(true) {
    var step = _step;
    if (pos.contents >= len || pos.contents < 0) {
      return step;
    }
    var cur = pos.contents;
    var jump = getJump(arr, pos);
    pos.contents = jump + pos.contents | 0;
    arr[cur] = jump + 1 | 0;
    _step = step + 1 | 0;
    continue ;
  };
}

function part2(arr, pos, _step) {
  while(true) {
    var step = _step;
    if (pos.contents >= len || pos.contents < 0) {
      return step;
    }
    var cur = pos.contents;
    var jump = getJump(arr, pos);
    pos.contents = jump + pos.contents | 0;
    if (jump >= 3) {
      arr[cur] = jump - 1 | 0;
    } else {
      arr[cur] = jump + 1 | 0;
    }
    _step = step + 1 | 0;
    continue ;
  };
}

console.log(part1(arr, pos, 0));

var something = -112;

exports.arr = arr;
exports.len = len;
exports.pos = pos;
exports.something = something;
exports.getJump = getJump;
exports.part1 = part1;
exports.part2 = part2;
/* arr Not a pure module */
